version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: Hl7.Fhir.Specification.STU3
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: Microsoft.Extensions.Logging.Abstractions
    versions:
    - 5.0.0
